### ISSUE TITLE
Where should I put secrets.py?

### ISSUE THREAD

**Issue by sgbaird** [adafruit/Adafruit_CircuitPython_HTTPServer#13]
In `lib`? At the same level as `code.py`? Doesn't matter?

**Comment by askpatrickw** [comment]
Hi @sgbaird, you can put it in either place. `import secrerts` will work either way.

The convention is to put `secrets.py` along side your `code.py`.  If you have more questions,  checkout the CircuitPython Discord https://adafru.it/discord or Forums https://forums.adafruit.com/
