### ISSUE TITLE
Wrong example in MDNS section of the docs

### ISSUE THREAD

**Issue by foxy82** [adafruit/Adafruit_CircuitPython_HTTPServer#39]
Here the example in the MDNS section of the docs is the cpu_information example not the mdns example that is in the repo.

https://docs.circuitpython.org/projects/httpserver/en/latest/examples.html

**Comment by jposada202020** [comment]
Thank you, you are right! we could change this line with the correct line here.

https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/blob/874d3ed886d9015e57b82cc757dd283ca57b2300/docs/examples.rst?plain=1#L29

Care to make a PR, if not I could do it.

Thanks again :)
