### ISSUE TITLE
request.form_data.get(...) returns the string "None" if a field doesn't exist

### ISSUE THREAD

**Issue by radair6000** [adafruit/Adafruit_CircuitPython_HTTPServer#69]
Hi,

The method [request.form_data.get](https://docs.circuitpython.org/projects/httpserver/en/latest/api.html#adafruit_httpserver.request.FormData.get) seems to return the string "None" if the requested field doesn't exist. Is should probably return the NoneType None?

**Comment by michalpokusa** [comment]
Hi, I added the fix in the #67 PR, if you can, please download this version of the lib and test again. Thanks!

**Comment by radair6000** [comment]
Hi again, I finally managed to test this now (sorry for taking so long), and it seems to be working great, thanks!
