### ISSUE TITLE
HTTPServer stops working on CircuitPython version >= 9.0

### ISSUE THREAD

**Issue by gmos** [adafruit/Adafruit_CircuitPython_HTTPServer#92]
HTTPServer stops working on CircuitPython version >= 9.0

Around line 207 in server.py it is assumed that `sock.setsockopt(socket_source.SOL_SOCKET, socket_source.SO_REUSEADDR, 1)` would work as of CircuitPython version 9.0.  Unfortunately it doesn't and raises an `OSError: [Errno 95] EOPNOTSUPP`.

Perhaps better in the circuitpython implementations to just try to set SO_REUSEADDR and catch + ignore the error.

**Comment by dhalbert** [comment]
Which board? This is fixed in 9.0.1 for Pico W.

**Comment by michalpokusa** [comment]
Duplicate of #90?

**Comment by gmos** [comment]
Indeed a duplicate of https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/issues/90 .
And it was on 9.0.0  I'll upgrade to 9.0.1 and retry.
